### ISSUE TITLE
Conﬁguration of block numbers in different stages

### ISSUE THREAD

**Issue by sbl1996** [danczs/Visformer#7]
Visformer have 7, 4, 4 blocks in stages S1, S2, S3, which is somewhat different from common configurations like ResNets. ResNets put the most blocks in stage 3 where the image size is 14x14, while Visformer put the most blocks in S1 where the image size is 28x28. Did you conduct some experiments and find your configuration better than ResNets in terms of performance and accuracy? I would appreciate it if you could provide these experiment results or your thoughts on it. Thank you!

**Comment by danczs** [comment]
Hi, that is a good question. In fact, we didn't specifically design the block numbers. Deit-S has 12 blocks. So when we split the network to 3 stages, the block numbers are 4, 4, 4 in S1, S2, and S3. Afterwards, we remove the self-attention in S1 and insert more block to it to balance the complexity. That's why the stage numbers are 7, 4, 4.
Therefore, we think the ResNet configuration (3, 4, 6, 3) may work better and there must be other better stage configurations. We have find very different stage configurations in other vision transformer work. e.g. swin transformer: [2,2,6,2] and cswin transformer: [1, 2, 21, 1].  CSWin Transformer also changed the architecture width & depth, and found 'deep-narrow' architecture is better, although we find it will increase the inference time. We don't have too many results now but we are working on it and expect to release better visformer nets.

**Comment by danczs** [comment]
We optimize the architecture configuration (including the stage configuration) of Visformer and propose VisformerV2.  For more details, please refer to https://arxiv.org/abs/2104.12533.

**Comment by sbl1996** [comment]
Amazing work! The new results in Table IX and Table XII are very interesting. Although VisformerV2-S is slower than Visformer-S in classification, the detection FPS is improved and AP is much better. It provides a perspective for architecture design of classification and detection. I have some suggestions that may be helpful.

1. To measure the inference efficiency, throughput (image/s) might be more common than batch time, although they are equivalent. You may follow the Table 5 of DeiT[1].

2. In Table IX, the comparison of VisformerV2-S to Visformer-S might be unfair, because the batch time of VisformerV2-S is significantly increased. You may increase the block numbers of Visformer-S to get a model with similar batch time to VisformerV2-S and compare their performance.

[1] Touvron, Hugo, Matthieu Cord, Matthijs Douze, Francisco Massa, Alexandre Sablayrolles and Herv'e J'egou. “Training data-efficient image transformers & distillation through attention.” ICML (2021).

**Comment by danczs** [comment]
Thanks for your helpful suggestions! We will try to evalutate the throughput of the models. 
As for the comparison of VisformerV2-S and Visformer-S, aligning the batch time is a good idea, but it will the further increase the FLOPs of Visformer-S. And when the models are transferd to the down-stream task, the FPS  sometimes is more consistent with FLOPs . So we think Visformer-S and VisformerV2-S are models with different properties and should be used depending on applications.
